export class InfectionLineDetail{
    constructor(stringToConvert:any){
        this.InfectionID = stringToConvert.InfectionID;
        this.InfectionEventID = stringToConvert.InfectionEventID;
        this.MRN = stringToConvert.MRN;
        this.EventClassNM = stringToConvert.EventClassNM;
        this.AdmitDT = new Date(stringToConvert.AdmitDT);
        this.DischargeDT = stringToConvert.DischargeDT;
        this.EventTypeNM = stringToConvert.EventTypeNM;
        this.HospitalAccountID = stringToConvert.HospitalAccountID;
        this.EpicPatientTypeDSC = stringToConvert.EpicPatientTypeDSC;
        this.QuarterNM = stringToConvert.QuarterNM;
        this.MonthNM = stringToConvert.MonthNM;
        this.LastNM = stringToConvert.LastNM;
        this.FirstNM = stringToConvert.FirstNM;
        this.MiddleNM = stringToConvert.MiddleNM;
        this.BirthDT = new Date(stringToConvert.BirthDT);
        this.AgeAtEventAMT = stringToConvert.AgeAtEventAMT;
        this.GenderCD = stringToConvert.GenderCD;
        this.FacilityNM = stringToConvert.FacilityNM;
        this.DepartmentNM = stringToConvert.DepartmentNM;
        this.RoomNM = stringToConvert.RoomNM;
        this.PhysicianNM = stringToConvert.PhysicianNM;
        this.ExpiredFLG = stringToConvert.ExpiredFLG;
        this.ContributedToDeathFLG = stringToConvert.ContributedToDeathFLG;
        this.CultureDT = stringToConvert.CultureDT;
        this.CultureSourceNM = stringToConvert.CultureSourceNM;
        this.OrganismDSC = stringToConvert.OrganismDSC;
        this.InjuryFLG = stringToConvert.InjuryFLG;
        this.EventDT = new Date(stringToConvert.EventDT);
        this.IncludeInSystemObjectiveFLG = stringToConvert.IncludeInSystemObjectiveFLG;
    }
    public InfectionID: number;
    public InfectionEventID:string;
    public MRN:string;
    public EventClassNM:string;
    public AdmitDT:Date;
    public DischargeDT:Date;
    public EventTypeNM:string;
    public HospitalAccountID:number;
    public EpicPatientTypeDSC:string;
    public QuarterNM:string;
    public MonthNM:string;
    public LastNM:string;
    public FirstNM:string;
    public MiddleNM:string;
    public BirthDT:Date;
    public AgeAtEventAMT:number;
    public GenderCD:string;
    public FacilityNM:string;
    public DepartmentNM:string;
    public RoomNM:string;
    public PhysicianNM:string;
    public ExpiredFLG:string;
    public ContributedToDeathFLG:string;
    public CultureDT:string;
    public CultureSourceNM:string;
    public OrganismDSC:string;
    public InjuryFLG:string;
    public EventDT:Date;
    public IncludeInSystemObjectiveFLG:string;
}