import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class MockService {
  public infectiousDiseaseRecords = {
    "count": 3493,
    "records": [
      {
        "data": {
          "ID": "1",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "1",
          "InfectionEventID": "19-1-HAI",
          "MRN": "2184880",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2019-12-28T00:00:00",
          "DischargeDT": "2020-01-03T00:00:00",
          "EventTypeNM": "SSI-FUSN",
          "HospitalAccountID": "706551837",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "4Q",
          "MonthNM": "DEC",
          "LastNM": "TURNER-SAXTON",
          "FirstNM": "ETHEL",
          "MiddleNM": "NULL",
          "BirthDT": "1944-11-04T00:00:00",
          "AgeAtEventAMT": "-99.0000",
          "GenderCD": "F",
          "FacilityNM": "TG Tacoma General Hospital (TG)",
          "DepartmentNM": "GSH IPR",
          "RoomNM": "NULL",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "NULL",
          "CultureSourceNM": "NULL",
          "OrganismDSC": "NULL",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "2",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "2",
          "InfectionEventID": "17-2-HAI",
          "MRN": "3792799",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2017-02-14T00:00:00",
          "DischargeDT": "2017-03-09T00:00:00",
          "EventTypeNM": "VAC",
          "HospitalAccountID": "702138382",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "FEB",
          "LastNM": "NOTCH",
          "FirstNM": "ARLEN",
          "MiddleNM": "J",
          "BirthDT": "1936-05-22T00:00:00",
          "AgeAtEventAMT": "80.0000",
          "GenderCD": "M",
          "FacilityNM": "Auburn Medical Center (AMC)",
          "DepartmentNM": "AMC INTENSIVE CARE UNIT",
          "RoomNM": "215",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "NULL",
          "CultureSourceNM": "NULL",
          "OrganismDSC": "NULL",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "3",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "3",
          "InfectionEventID": "17-3-HAI",
          "MRN": "384834",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2017-09-24T00:00:00",
          "DischargeDT": "2017-11-16T00:00:00",
          "EventTypeNM": "MRSA",
          "HospitalAccountID": "702954109",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "4Q",
          "MonthNM": "OCT",
          "LastNM": "SARGENT",
          "FirstNM": "ROBERT",
          "MiddleNM": "D",
          "BirthDT": "1956-10-09T00:00:00",
          "AgeAtEventAMT": "61.0000",
          "GenderCD": "M",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH 5 PCU PROGRESSIVE CARE UNIT",
          "RoomNM": "504",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "NULL",
          "CultureSourceNM": "Bronch wash",
          "OrganismDSC": "MRSA",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "4",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "4",
          "InfectionEventID": "17-4-HAI",
          "MRN": "803325",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2017-05-16T00:00:00",
          "DischargeDT": "2017-05-23T00:00:00",
          "EventTypeNM": "REPR-EMET",
          "HospitalAccountID": "702479801",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "2Q",
          "MonthNM": "MAY",
          "LastNM": "AGOSTINI",
          "FirstNM": "KYLIE",
          "MiddleNM": "NULL",
          "BirthDT": "1990-01-06T00:00:00",
          "AgeAtEventAMT": "27.0000",
          "GenderCD": "F",
          "FacilityNM": "TG Tacoma General Hospital (TG)",
          "DepartmentNM": "TG 3 RAINIER WOMEN NEWBORN CENTER",
          "RoomNM": "427",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "NULL",
          "CultureSourceNM": "NULL",
          "OrganismDSC": "NULL",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "5",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "5",
          "InfectionEventID": "17-5-HAI",
          "MRN": "3853556",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2017-08-15T00:00:00",
          "DischargeDT": "2099-12-31T00:00:00",
          "EventTypeNM": "PNEUMONIA",
          "HospitalAccountID": "702808060",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "3Q",
          "MonthNM": "AUG",
          "LastNM": "STRAIGHT",
          "FirstNM": "DAVID",
          "MiddleNM": "LEE",
          "BirthDT": "1957-03-30T00:00:00",
          "AgeAtEventAMT": "60.0000",
          "GenderCD": "M",
          "FacilityNM": "Auburn Medical Center (AMC)",
          "DepartmentNM": "AMC PROGRESSIVE CARE UNIT",
          "RoomNM": "443",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NULL",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "NULL",
          "CultureSourceNM": "NULL",
          "OrganismDSC": "NA",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "6",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "6",
          "InfectionEventID": "17-6-HAI",
          "MRN": "5137",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2017-08-16T00:00:00",
          "DischargeDT": "2099-12-31T00:00:00",
          "EventTypeNM": "CVS",
          "HospitalAccountID": "702814424",
          "EpicPatientTypeDSC": "Emergency",
          "QuarterNM": "3Q",
          "MonthNM": "AUG",
          "LastNM": "CANEVA",
          "FirstNM": "CHRISTOPHER",
          "MiddleNM": "L",
          "BirthDT": "1961-09-27T00:00:00",
          "AgeAtEventAMT": "55.0000",
          "GenderCD": "M",
          "FacilityNM": "Auburn Medical Center (AMC)",
          "DepartmentNM": "AMC PROGRESSIVE CARE UNIT",
          "RoomNM": "435",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NULL",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "NULL",
          "CultureSourceNM": "NULL",
          "OrganismDSC": "NA",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "7",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "7",
          "InfectionEventID": "17-7-HAI",
          "MRN": "176873",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2017-08-02T00:00:00",
          "DischargeDT": "2017-08-31T00:00:00",
          "EventTypeNM": "PNEUMONIA",
          "HospitalAccountID": "702763352",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "3Q",
          "MonthNM": "AUG",
          "LastNM": "CURRAN",
          "FirstNM": "LENORA",
          "MiddleNM": "J",
          "BirthDT": "1942-01-31T00:00:00",
          "AgeAtEventAMT": "75.0000",
          "GenderCD": "F",
          "FacilityNM": "Auburn Medical Center (AMC)",
          "DepartmentNM": "AMC PROGRESSIVE CARE UNIT",
          "RoomNM": "440",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "Yes",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "NULL",
          "CultureSourceNM": "NULL",
          "OrganismDSC": "NULL",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "8",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "8",
          "InfectionEventID": "17-8-HAI",
          "MRN": "3058098",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2017-09-17T00:00:00",
          "DischargeDT": "2099-12-31T00:00:00",
          "EventTypeNM": "PNEUMONIA",
          "HospitalAccountID": "702927098",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "3Q",
          "MonthNM": "SEP",
          "LastNM": "BRACKEN",
          "FirstNM": "BEVERLY",
          "MiddleNM": "E",
          "BirthDT": "1960-03-13T00:00:00",
          "AgeAtEventAMT": "57.0000",
          "GenderCD": "F",
          "FacilityNM": "Auburn Medical Center (AMC)",
          "DepartmentNM": "AMC PROGRESSIVE CARE UNIT",
          "RoomNM": "434",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NULL",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "NULL",
          "CultureSourceNM": "NULL",
          "OrganismDSC": "NULL",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "9",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "9",
          "InfectionEventID": "18-9-HAI",
          "MRN": "3095211",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2018-12-14T00:00:00",
          "DischargeDT": "2099-12-31T00:00:00",
          "EventTypeNM": "VAC",
          "HospitalAccountID": "704779810",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "NULL",
          "MonthNM": "NULL",
          "LastNM": "Friberg",
          "FirstNM": "Stephen",
          "MiddleNM": "P",
          "BirthDT": "1961-06-27T00:00:00",
          "AgeAtEventAMT": "57.0000",
          "GenderCD": "M",
          "FacilityNM": "Auburn Medical Center (AMC)",
          "DepartmentNM": "AMC INTENSIVE CARE UNIT",
          "RoomNM": "206",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "NULL",
          "CultureSourceNM": "NULL",
          "OrganismDSC": "NULL",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "10",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "10",
          "InfectionEventID": "19-10-HAI",
          "MRN": "2593714",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2019-06-24T00:00:00",
          "DischargeDT": "2019-07-19T00:00:00",
          "EventTypeNM": "VAC",
          "HospitalAccountID": "705663244",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "2Q",
          "MonthNM": "JUN",
          "LastNM": "HICKEL",
          "FirstNM": "TRACY",
          "MiddleNM": "NULL",
          "BirthDT": "1964-02-26T00:00:00",
          "AgeAtEventAMT": "-64.0000",
          "GenderCD": "M",
          "FacilityNM": "Auburn Medical Center (AMC)",
          "DepartmentNM": "AMC INTENSIVE CARE UNIT",
          "RoomNM": "206",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "YES",
          "ContributedToDeathFLG": "NO",
          "CultureDT": "NULL",
          "CultureSourceNM": "NULL",
          "OrganismDSC": "NULL",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "NO"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "11",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "11",
          "InfectionEventID": "19-11-HAI",
          "MRN": "2676124",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2019-07-29T00:00:00",
          "DischargeDT": "2019-08-23T00:00:00",
          "EventTypeNM": "VAC",
          "HospitalAccountID": "705824673",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "3Q",
          "MonthNM": "AUG",
          "LastNM": "KEYES",
          "FirstNM": "DANIEL",
          "MiddleNM": "D",
          "BirthDT": "1965-08-25T00:00:00",
          "AgeAtEventAMT": "-65.0000",
          "GenderCD": "M",
          "FacilityNM": "Auburn Medical Center (AMC)",
          "DepartmentNM": "AMC INTENSIVE CARE UNIT",
          "RoomNM": "204",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "NULL",
          "CultureSourceNM": "NULL",
          "OrganismDSC": "NULL",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "NO"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "12",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "12",
          "InfectionEventID": "19-12-HAI",
          "MRN": "2879268",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2019-08-25T00:00:00",
          "DischargeDT": "2019-09-16T00:00:00",
          "EventTypeNM": "VAC",
          "HospitalAccountID": "705948433",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "3Q",
          "MonthNM": "SEP",
          "LastNM": "HIDALGO",
          "FirstNM": "Kristopher",
          "MiddleNM": "NULL",
          "BirthDT": "1989-03-07T00:00:00",
          "AgeAtEventAMT": "-89.0000",
          "GenderCD": "M",
          "FacilityNM": "Auburn Medical Center (AMC)",
          "DepartmentNM": "AMC INTENSIVE CARE UNIT",
          "RoomNM": "215",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "NULL",
          "CultureSourceNM": "NULL",
          "OrganismDSC": "NULL",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "NO"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "13",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "13",
          "InfectionEventID": "19-13-HAI",
          "MRN": "915622",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2019-11-26T00:00:00",
          "DischargeDT": "2019-12-04T00:00:00",
          "EventTypeNM": "VAC",
          "HospitalAccountID": "706402530",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "4Q",
          "MonthNM": "NOV",
          "LastNM": "FILLO",
          "FirstNM": "DAWN",
          "MiddleNM": "MI",
          "BirthDT": "1966-08-27T00:00:00",
          "AgeAtEventAMT": "-66.0000",
          "GenderCD": "F",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH INTENSIVE CARE UNIT",
          "RoomNM": "243",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "NULL",
          "CultureSourceNM": "NULL",
          "OrganismDSC": "NULL",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "NO"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "14",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "14",
          "InfectionEventID": "19-14-HAI",
          "MRN": "671348",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2019-12-01T00:00:00",
          "DischargeDT": "2099-12-31T00:00:00",
          "EventTypeNM": "IVAC",
          "HospitalAccountID": "706415799",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "4Q",
          "MonthNM": "DEC",
          "LastNM": "DOSS",
          "FirstNM": "HAROLD",
          "MiddleNM": "A",
          "BirthDT": "1951-03-04T00:00:00",
          "AgeAtEventAMT": "-51.0000",
          "GenderCD": "M",
          "FacilityNM": "Auburn Medical Center (AMC)",
          "DepartmentNM": "AMC INTENSIVE CARE UNIT",
          "RoomNM": "211",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "NULL",
          "CultureSourceNM": "NULL",
          "OrganismDSC": "NULL",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "NO"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "15",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "15",
          "InfectionEventID": "19-15-HAI",
          "MRN": "2189418",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2019-12-17T00:00:00",
          "DischargeDT": "2099-12-31T00:00:00",
          "EventTypeNM": "IVAC",
          "HospitalAccountID": "706499036",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "4Q",
          "MonthNM": "DEC",
          "LastNM": "ORGOVAN",
          "FirstNM": "MICHELLE",
          "MiddleNM": "C",
          "BirthDT": "1973-06-27T00:00:00",
          "AgeAtEventAMT": "-73.0000",
          "GenderCD": "M",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH INTENSIVE CARE UNIT",
          "RoomNM": "242",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NULL",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "NULL",
          "CultureSourceNM": "NULL",
          "OrganismDSC": "NULL",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "NO"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "16",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "16",
          "InfectionEventID": "10-1-HAI",
          "MRN": "1343329",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2020-06-04T00:00:00",
          "DischargeDT": "2099-12-31T00:00:00",
          "EventTypeNM": "CA-UTI",
          "HospitalAccountID": "707269186",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "2Q",
          "MonthNM": "JUN",
          "LastNM": "CHRISTY",
          "FirstNM": "SUSAN",
          "MiddleNM": "E",
          "BirthDT": "1955-12-01T00:00:00",
          "AgeAtEventAMT": "64.0000",
          "GenderCD": "F",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH 5 PCU PROGRESSIVE CARE UNIT",
          "RoomNM": "821",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "6/9/2010",
          "CultureSourceNM": "URINE",
          "OrganismDSC": "ESCHERICHIA COLI",
          "InjuryFLG": "1",
          "EventDT": "2020-06-09T00:00:00",
          "IncludeInSystemObjectiveFLG": "YES"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "17",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "17",
          "InfectionEventID": "12-1-HAI",
          "MRN": "46851",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2011-12-17T00:00:00",
          "DischargeDT": "2012-01-04T00:00:00",
          "EventTypeNM": "CLABSI",
          "HospitalAccountID": "11448870",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "HANSEN",
          "FirstNM": "HELEN",
          "MiddleNM": "M",
          "BirthDT": "1946-01-27T00:00:00",
          "AgeAtEventAMT": "65.0000",
          "GenderCD": "F",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH 5 DALLY INTENSIVE CARE-CRITICAL CARE",
          "RoomNM": "512",
          "PhysicianNM": "LEE, MARTIN",
          "ExpiredFLG": "YES",
          "ContributedToDeathFLG": "NO",
          "CultureDT": "1/2/2012",
          "CultureSourceNM": "BLOOD",
          "OrganismDSC": "SERRATIA MARCESCENS",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "18",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "18",
          "InfectionEventID": "12-2-HAI",
          "MRN": "1796084",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2011-12-13T00:00:00",
          "DischargeDT": "2011-12-19T00:00:00",
          "EventTypeNM": "CDIFF",
          "HospitalAccountID": "11432737",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "HENDRICKSON",
          "FirstNM": "LINDA",
          "MiddleNM": "G",
          "BirthDT": "1947-04-02T00:00:00",
          "AgeAtEventAMT": "64.0000",
          "GenderCD": "F",
          "FacilityNM": "TG Tacoma General Hospital (TG)",
          "DepartmentNM": "TG 4 RAINIER INTERMEDIATE CARE TRANSFER",
          "RoomNM": "431",
          "PhysicianNM": "MARCEAM",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/3/2012",
          "CultureSourceNM": "STOOL",
          "OrganismDSC": "CLOSTRIDIUM DIFFICILE",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "19",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "19",
          "InfectionEventID": "12-3-HAI",
          "MRN": "760712",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-04T00:00:00",
          "DischargeDT": "2099-12-31T00:00:00",
          "EventTypeNM": "CA-UTI",
          "HospitalAccountID": "11493214",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "LOLLAND",
          "FirstNM": "WYNN",
          "MiddleNM": "NULL",
          "BirthDT": "1959-09-09T00:00:00",
          "AgeAtEventAMT": "52.0000",
          "GenderCD": "M",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH A MEADOW REHABILITATION",
          "RoomNM": "NULL",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NULL",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/4/2012",
          "CultureSourceNM": "URINE",
          "OrganismDSC": "PSEUDOMONAS AERUGINOSA",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "20",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "20",
          "InfectionEventID": "12-4-HAI",
          "MRN": "2969503",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2011-12-06T00:00:00",
          "DischargeDT": "2099-12-31T00:00:00",
          "EventTypeNM": "MRSA-NARES",
          "HospitalAccountID": "11414381",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "HWANG",
          "FirstNM": "BABY BOY",
          "MiddleNM": "NULL",
          "BirthDT": "2011-12-06T00:00:00",
          "AgeAtEventAMT": "0.0000",
          "GenderCD": "M",
          "FacilityNM": "TG Tacoma General Hospital (TG)",
          "DepartmentNM": "TG 2 RAINIER NEONATAL INTENSIVE CARE",
          "RoomNM": "A-02",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NO",
          "CultureDT": "1/4/2012",
          "CultureSourceNM": "NARES",
          "OrganismDSC": "MRSA",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "21",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "21",
          "InfectionEventID": "12-5-HAI",
          "MRN": "2867628",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-10T00:00:00",
          "DischargeDT": "2012-01-18T00:00:00",
          "EventTypeNM": "CLABSI",
          "HospitalAccountID": "11508554",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "AL-HAWASLI",
          "FirstNM": "YASMEEN",
          "MiddleNM": "NULL",
          "BirthDT": "2009-11-26T00:00:00",
          "AgeAtEventAMT": "2.0000",
          "GenderCD": "F",
          "FacilityNM": "MB Childrens Hospital (MBCH)",
          "DepartmentNM": "MB INFUSION SPECIALTY SERVICES",
          "RoomNM": "NULL",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/9/2012",
          "CultureSourceNM": "BLOOD",
          "OrganismDSC": "STAPH EPI",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "22",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "22",
          "InfectionEventID": "12-6-HAI",
          "MRN": "1351642",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2011-12-13T00:00:00",
          "DischargeDT": "2012-01-14T00:00:00",
          "EventTypeNM": "CDIFF",
          "HospitalAccountID": null,
          "EpicPatientTypeDSC": "NULL",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "MYERS",
          "FirstNM": "RONALD",
          "MiddleNM": "L",
          "BirthDT": "1932-01-28T00:00:00",
          "AgeAtEventAMT": "79.0000",
          "GenderCD": "M",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH 5 DALLY INTENSIVE CARE-STEP DOWN",
          "RoomNM": "504/608/637",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/10/2012",
          "CultureSourceNM": "STOOL",
          "OrganismDSC": "CLOSTRIDIUM DIFFICILE",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "23",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "23",
          "InfectionEventID": "12-7-HAI",
          "MRN": "2957760",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2011-10-14T00:00:00",
          "DischargeDT": "2012-02-23T00:00:00",
          "EventTypeNM": "CLABSI",
          "HospitalAccountID": "11262602",
          "EpicPatientTypeDSC": "Newborn",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "QUINIO-ROLINSKI",
          "FirstNM": "BABY GIRL",
          "MiddleNM": "NULL",
          "BirthDT": "2011-10-14T00:00:00",
          "AgeAtEventAMT": "0.0000",
          "GenderCD": "F",
          "FacilityNM": "TG Tacoma General Hospital (TG)",
          "DepartmentNM": "TG 2 RAINIER NEONATAL INTENSIVE CARE",
          "RoomNM": "D-01",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/11/2012",
          "CultureSourceNM": "BLOOD",
          "OrganismDSC": "STAPH CAPITIS",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "24",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "24",
          "InfectionEventID": "12-8-HAI",
          "MRN": "2290652",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2011-08-26T00:00:00",
          "DischargeDT": "2011-09-09T00:00:00",
          "EventTypeNM": "SSI-COLO",
          "HospitalAccountID": "11117297",
          "EpicPatientTypeDSC": "Surgical-Inpatient PM",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "MORRIS",
          "FirstNM": "BARBARA",
          "MiddleNM": "J",
          "BirthDT": "1932-10-22T00:00:00",
          "AgeAtEventAMT": "78.0000",
          "GenderCD": "F",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH OPERATING ROOM",
          "RoomNM": "374",
          "PhysicianNM": "PETTY",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/12/2012",
          "CultureSourceNM": "SSI",
          "OrganismDSC": "MRSA",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "25",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "25",
          "InfectionEventID": "12-9-HAI",
          "MRN": "2920040",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-12-30T00:00:00",
          "DischargeDT": "2012-01-01T00:00:00",
          "EventTypeNM": "SSI-CSEC",
          "HospitalAccountID": null,
          "EpicPatientTypeDSC": "NULL",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "SAMOA",
          "FirstNM": "KATHLEEN",
          "MiddleNM": "V",
          "BirthDT": "1988-10-27T00:00:00",
          "AgeAtEventAMT": "24.0000",
          "GenderCD": "F",
          "FacilityNM": "TG Tacoma General Hospital (TG)",
          "DepartmentNM": "TG 2 RAINIER BIRTH CENTER",
          "RoomNM": "311",
          "PhysicianNM": "HITCHCOCK",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/12/2012",
          "CultureSourceNM": "SSI",
          "OrganismDSC": "PSEUDOMONAS AERUGINOSA",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "26",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "26",
          "InfectionEventID": "12-10-HAI",
          "MRN": "2974733",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-01T00:00:00",
          "DischargeDT": "2012-01-28T00:00:00",
          "EventTypeNM": "CA-UTI",
          "HospitalAccountID": "11485412",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "OSBORNE",
          "FirstNM": "ELIZABETH",
          "MiddleNM": "E",
          "BirthDT": "2011-09-06T00:00:00",
          "AgeAtEventAMT": "0.0000",
          "GenderCD": "F",
          "FacilityNM": "MB Childrens Hospital (MBCH)",
          "DepartmentNM": "MB PEDIATRIC INTENSIVE CARE",
          "RoomNM": "795",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/13/2012",
          "CultureSourceNM": "URINE",
          "OrganismDSC": "ESCHERICHIA COLI",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "27",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "27",
          "InfectionEventID": "12-11-HAI",
          "MRN": "2974733",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-01T00:00:00",
          "DischargeDT": "2012-01-28T00:00:00",
          "EventTypeNM": "CLABSI",
          "HospitalAccountID": "11485412",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "OSBORNE",
          "FirstNM": "ELIZABETH",
          "MiddleNM": "E",
          "BirthDT": "2011-09-06T00:00:00",
          "AgeAtEventAMT": "0.0000",
          "GenderCD": "F",
          "FacilityNM": "MB Childrens Hospital (MBCH)",
          "DepartmentNM": "MB PEDIATRIC INTENSIVE CARE",
          "RoomNM": "795",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/13/2012",
          "CultureSourceNM": "BLOOD",
          "OrganismDSC": "ENTEROCOCCUS FAECALIS",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "28",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "28",
          "InfectionEventID": "12-12-HAI",
          "MRN": "2974733",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-01T00:00:00",
          "DischargeDT": "2099-12-31T00:00:00",
          "EventTypeNM": "ESBL",
          "HospitalAccountID": "11485412",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "OSBORNE",
          "FirstNM": "ELIZABETH",
          "MiddleNM": "E",
          "BirthDT": "2011-09-06T00:00:00",
          "AgeAtEventAMT": "0.0000",
          "GenderCD": "F",
          "FacilityNM": "MB Childrens Hospital (MBCH)",
          "DepartmentNM": "MB PEDIATRIC INTENSIVE CARE",
          "RoomNM": "795",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/13/2012",
          "CultureSourceNM": "URINE; SPUTUM",
          "OrganismDSC": "ESCHERICHIA COLI",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "29",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "29",
          "InfectionEventID": "12-13-HAI",
          "MRN": "2109707",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-06T00:00:00",
          "DischargeDT": "2099-12-31T00:00:00",
          "EventTypeNM": "MRSA-NARES",
          "HospitalAccountID": "11501503",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "HUBBARD",
          "FirstNM": "RICHARD",
          "MiddleNM": "A",
          "BirthDT": "1929-04-23T00:00:00",
          "AgeAtEventAMT": "82.0000",
          "GenderCD": "F",
          "FacilityNM": "Allenmore (AH)",
          "DepartmentNM": "AH 2 WEST PROGRESSIVE CARE",
          "RoomNM": "NULL",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NO",
          "CultureDT": "1/13/2012",
          "CultureSourceNM": "NARES",
          "OrganismDSC": "MRSA",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "30",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "30",
          "InfectionEventID": "12-14-HAI",
          "MRN": "1967856",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-08T00:00:00",
          "DischargeDT": "2012-02-06T00:00:00",
          "EventTypeNM": "CLABSI",
          "HospitalAccountID": "11504242",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "ELLIS",
          "FirstNM": "PAUL",
          "MiddleNM": "NULL",
          "BirthDT": "1946-09-14T00:00:00",
          "AgeAtEventAMT": "65.0000",
          "GenderCD": "M",
          "FacilityNM": "TG Tacoma General Hospital (TG)",
          "DepartmentNM": "TG 4 RAINIER INTERMEDIATE CARE TRANSFER",
          "RoomNM": "404",
          "PhysicianNM": "DELCAMPO",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/15/2012",
          "CultureSourceNM": "BLOOD",
          "OrganismDSC": "ENTEROCOCCUS FAECIUM",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "31",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "31",
          "InfectionEventID": "12-15-HAI",
          "MRN": "1967856",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-08T00:00:00",
          "DischargeDT": "2099-12-31T00:00:00",
          "EventTypeNM": "VRE",
          "HospitalAccountID": "11504242",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "ELLIS",
          "FirstNM": "PAUL",
          "MiddleNM": "G",
          "BirthDT": "1946-09-17T00:00:00",
          "AgeAtEventAMT": "65.0000",
          "GenderCD": "M",
          "FacilityNM": "TG Tacoma General Hospital (TG)",
          "DepartmentNM": "TG 4 RAINIER INTERMEDIATE CARE TRANSFER",
          "RoomNM": "404",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/15/2012",
          "CultureSourceNM": "BLOOD",
          "OrganismDSC": "ENTERCOCCUS FAECIUM",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "32",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "32",
          "InfectionEventID": "12-16-HAI",
          "MRN": "2855899",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-13T00:00:00",
          "DischargeDT": "2012-01-19T00:00:00",
          "EventTypeNM": "CA-UTI",
          "HospitalAccountID": "11417518",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "MATSON",
          "FirstNM": "HEIDI",
          "MiddleNM": "NULL",
          "BirthDT": "1982-03-11T00:00:00",
          "AgeAtEventAMT": "29.0000",
          "GenderCD": "F",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH 1 MEADOW MOTHER/BABY",
          "RoomNM": "NULL",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/16/2012",
          "CultureSourceNM": "URINE",
          "OrganismDSC": "ESCHERICHIA COLI",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "33",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "33",
          "InfectionEventID": "12-17-HAI",
          "MRN": "1374849",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-09T00:00:00",
          "DischargeDT": "2099-12-31T00:00:00",
          "EventTypeNM": "MRSA-NARES",
          "HospitalAccountID": "11504324",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "MORALES",
          "FirstNM": "JORGE",
          "MiddleNM": "A",
          "BirthDT": "1959-10-12T00:00:00",
          "AgeAtEventAMT": "52.0000",
          "GenderCD": "M",
          "FacilityNM": "TG Tacoma General Hospital (TG)",
          "DepartmentNM": "TG 8 PHILIP CORONARY CARE",
          "RoomNM": "NULL",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NO",
          "CultureDT": "1/16/2012",
          "CultureSourceNM": "NARES",
          "OrganismDSC": "MRSA",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "34",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "34",
          "InfectionEventID": "12-18-HAI",
          "MRN": "272859",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-13T00:00:00",
          "DischargeDT": "2099-12-31T00:00:00",
          "EventTypeNM": "CA-UTI",
          "HospitalAccountID": "11519257",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "Reiff",
          "FirstNM": "Barbara",
          "MiddleNM": "NULL",
          "BirthDT": "1954-09-09T00:00:00",
          "AgeAtEventAMT": "57.0000",
          "GenderCD": "M",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH A MEADOW REHABILITATION",
          "RoomNM": "NULL",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NULL",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/18/2012",
          "CultureSourceNM": "URINE",
          "OrganismDSC": "ESBL",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "35",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "35",
          "InfectionEventID": "12-19-HAI",
          "MRN": "2972745",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-10T00:00:00",
          "DischargeDT": "2012-01-22T00:00:00",
          "EventTypeNM": "CDIFF",
          "HospitalAccountID": null,
          "EpicPatientTypeDSC": "NULL",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "NEELY",
          "FirstNM": "CHARLES",
          "MiddleNM": "A",
          "BirthDT": "1988-09-29T00:00:00",
          "AgeAtEventAMT": "23.0000",
          "GenderCD": "M",
          "FacilityNM": "TG Tacoma General Hospital (TG)",
          "DepartmentNM": "TG 4 OLYMPIC ADULT INTENSIVE CARE",
          "RoomNM": "589",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/18/2012",
          "CultureSourceNM": "STOOL",
          "OrganismDSC": "CLOSTRIDIUM DIFFICILE",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "36",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "36",
          "InfectionEventID": "12-20-HAI",
          "MRN": "62421",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-18T00:00:00",
          "DischargeDT": "2012-02-09T00:00:00",
          "EventTypeNM": "CDIFF",
          "HospitalAccountID": "11533781",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "ROBLES",
          "FirstNM": "MARY LOU",
          "MiddleNM": "NULL",
          "BirthDT": "1934-07-05T00:00:00",
          "AgeAtEventAMT": "77.0000",
          "GenderCD": "F",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH 6 DALLY MEDICAL INTERMEDIATE CARE",
          "RoomNM": "640/537",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/19/2012",
          "CultureSourceNM": "STOOL",
          "OrganismDSC": "CLOSTRIDIUM DIFFICILE",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "37",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "37",
          "InfectionEventID": "12-21-HAI",
          "MRN": "1095943",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2011-12-31T00:00:00",
          "DischargeDT": "2012-01-04T00:00:00",
          "EventTypeNM": "SSI-COLO",
          "HospitalAccountID": null,
          "EpicPatientTypeDSC": "NULL",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "MINOR",
          "FirstNM": "JOSEPH",
          "MiddleNM": "P",
          "BirthDT": "1951-03-16T00:00:00",
          "AgeAtEventAMT": "60.0000",
          "GenderCD": "M",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH OPERATING ROOM",
          "RoomNM": "531",
          "PhysicianNM": "MARSH",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/19/2012",
          "CultureSourceNM": "SSI",
          "OrganismDSC": "BF",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "38",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "38",
          "InfectionEventID": "12-22-HAI",
          "MRN": "599239",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-19T00:00:00",
          "DischargeDT": "2012-01-22T00:00:00",
          "EventTypeNM": "SSI-CSEC",
          "HospitalAccountID": "11423286",
          "EpicPatientTypeDSC": "Surgical-Inpatient AM",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "MAGILL",
          "FirstNM": "ERIN",
          "MiddleNM": "J",
          "BirthDT": "1983-02-08T00:00:00",
          "AgeAtEventAMT": "28.0000",
          "GenderCD": "F",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH 1 MEADOW MOTHER/BABY",
          "RoomNM": "139",
          "PhysicianNM": "SONG",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/19/2012",
          "CultureSourceNM": "NO CULTURE",
          "OrganismDSC": "NO CULTURE",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "39",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "39",
          "InfectionEventID": "12-23-HAI",
          "MRN": "1360475",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-15T00:00:00",
          "DischargeDT": "2012-01-28T00:00:00",
          "EventTypeNM": "CA-UTI",
          "HospitalAccountID": "11525762",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "WILSON",
          "FirstNM": "BERTHA",
          "MiddleNM": "NULL",
          "BirthDT": "1932-08-13T00:00:00",
          "AgeAtEventAMT": "79.0000",
          "GenderCD": "F",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH 4 RIVER ONCOLOGY",
          "RoomNM": "NULL",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/21/2012",
          "CultureSourceNM": "URINE (catheterized)",
          "OrganismDSC": "ESCHERICHIA COLI",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "40",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "40",
          "InfectionEventID": "12-24-HAI",
          "MRN": "2945637",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-09T00:00:00",
          "DischargeDT": "2012-01-10T00:00:00",
          "EventTypeNM": "SSI-VSHN",
          "HospitalAccountID": "11504354",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "MCKEE",
          "FirstNM": "ELIJAH",
          "MiddleNM": "J",
          "BirthDT": "2010-06-22T00:00:00",
          "AgeAtEventAMT": "1.0000",
          "GenderCD": "M",
          "FacilityNM": "MB Childrens Hospital (MBCH)",
          "DepartmentNM": "MB MEDICAL SURGICAL",
          "RoomNM": "NULL",
          "PhysicianNM": "ABDI",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/22/2012",
          "CultureSourceNM": "SSI",
          "OrganismDSC": "ENC",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "41",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "41",
          "InfectionEventID": "12-25-HAI",
          "MRN": "27742",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-16T00:00:00",
          "DischargeDT": "2012-01-28T00:00:00",
          "EventTypeNM": "MRSA",
          "HospitalAccountID": "11523254",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "Cridlebaugh",
          "FirstNM": "Ronald",
          "MiddleNM": "NULL",
          "BirthDT": "1931-11-30T00:00:00",
          "AgeAtEventAMT": "80.0000",
          "GenderCD": "M",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH A MEADOW REHABILITATION",
          "RoomNM": "NULL",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "No",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/23/2012",
          "CultureSourceNM": "PAROTID DRAINAGE",
          "OrganismDSC": "MRSA",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "42",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "42",
          "InfectionEventID": "12-26-HAI",
          "MRN": "924458",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-24T00:00:00",
          "DischargeDT": "2012-02-24T00:00:00",
          "EventTypeNM": "SSI-VHYS",
          "HospitalAccountID": "11486645",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "PUGH",
          "FirstNM": "KATHLEEN",
          "MiddleNM": "MI",
          "BirthDT": "1947-09-08T00:00:00",
          "AgeAtEventAMT": "64.0000",
          "GenderCD": "F",
          "FacilityNM": "TG Tacoma General Hospital (TG)",
          "DepartmentNM": "TG 4 RAINIER AMBULATORY CARE",
          "RoomNM": "422",
          "PhysicianNM": "Nickel",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/24/2012",
          "CultureSourceNM": "UNKNOWN",
          "OrganismDSC": "UNKNOWN",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "43",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "43",
          "InfectionEventID": "12-27-HAI",
          "MRN": "2746387",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-23T00:00:00",
          "DischargeDT": "2012-02-03T00:00:00",
          "EventTypeNM": "CA-UTI",
          "HospitalAccountID": "11541411",
          "EpicPatientTypeDSC": "Outpatient-Lab",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "BROWN",
          "FirstNM": "RENEE",
          "MiddleNM": "NULL",
          "BirthDT": "1948-03-14T00:00:00",
          "AgeAtEventAMT": "63.0000",
          "GenderCD": "F",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH 2 FOREST-MEADOW CARDIAC CARE",
          "RoomNM": "NULL",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/27/2012",
          "CultureSourceNM": "URINE",
          "OrganismDSC": "PROTEUS MIRIBILIS",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "44",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "44",
          "InfectionEventID": "12-28-HAI",
          "MRN": "466139",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-23T00:00:00",
          "DischargeDT": "2012-02-04T00:00:00",
          "EventTypeNM": "CLABSI",
          "HospitalAccountID": "11543536",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "GREENWOOD",
          "FirstNM": "ELIZABETH",
          "MiddleNM": "NULL",
          "BirthDT": "1996-07-08T00:00:00",
          "AgeAtEventAMT": "15.0000",
          "GenderCD": "F",
          "FacilityNM": "MB Childrens Hospital (MBCH)",
          "DepartmentNM": "MB MEDICAL SURGICAL",
          "RoomNM": "773",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/28/2012",
          "CultureSourceNM": "BLOOD",
          "OrganismDSC": "STAU",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "45",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "45",
          "InfectionEventID": "12-29-HAI",
          "MRN": "326206",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-26T00:00:00",
          "DischargeDT": "2012-02-11T00:00:00",
          "EventTypeNM": "CDIFF",
          "HospitalAccountID": "11555907",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "WEBER",
          "FirstNM": "HELEN",
          "MiddleNM": "NULL",
          "BirthDT": "1963-11-06T00:00:00",
          "AgeAtEventAMT": "48.0000",
          "GenderCD": "F",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH 6 DALLY MEDICAL INTERMEDIATE CARE",
          "RoomNM": "632",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/29/2012",
          "CultureSourceNM": "STOOL",
          "OrganismDSC": "CLOSTRIDIUM DIFFICILE",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "46",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "46",
          "InfectionEventID": "12-30-HAI",
          "MRN": "1180811",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-22T00:00:00",
          "DischargeDT": "2012-02-01T00:00:00",
          "EventTypeNM": "CDIFF",
          "HospitalAccountID": "11538877",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "MCKENZIE",
          "FirstNM": "MARCUS",
          "MiddleNM": "S",
          "BirthDT": "1995-10-04T00:00:00",
          "AgeAtEventAMT": "16.0000",
          "GenderCD": "M",
          "FacilityNM": "MB Childrens Hospital (MBCH)",
          "DepartmentNM": "MB MEDICAL SURGICAL",
          "RoomNM": "694",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/30/2012",
          "CultureSourceNM": "STOOL",
          "OrganismDSC": "CLOSTRIDIUM DIFFICILE",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "47",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "47",
          "InfectionEventID": "12-31-HAI",
          "MRN": "2867628",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-30T00:00:00",
          "DischargeDT": "2012-02-11T00:00:00",
          "EventTypeNM": "CLABSI",
          "HospitalAccountID": "11566948",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "AL-HAWASLI",
          "FirstNM": "YASMEEN",
          "MiddleNM": "NULL",
          "BirthDT": "2009-11-26T00:00:00",
          "AgeAtEventAMT": "2.0000",
          "GenderCD": "F",
          "FacilityNM": "MB Childrens Hospital (MBCH)",
          "DepartmentNM": "MB INFUSION SPECIALTY SERVICES",
          "RoomNM": "NULL",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/30/2012",
          "CultureSourceNM": "BLOOD",
          "OrganismDSC": "ENTEROCOCCUS FAECALIS",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "48",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "48",
          "InfectionEventID": "12-32-HAI",
          "MRN": "226627",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-06T00:00:00",
          "DischargeDT": "2012-01-13T00:00:00",
          "EventTypeNM": "CDIFF",
          "HospitalAccountID": "11502117",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "ROBERTS",
          "FirstNM": "LILLIAN",
          "MiddleNM": "NULL",
          "BirthDT": "1928-10-04T00:00:00",
          "AgeAtEventAMT": "83.0000",
          "GenderCD": "F",
          "FacilityNM": "Allenmore (AH)",
          "DepartmentNM": "AH 2 WEST PROGRESSIVE CARE",
          "RoomNM": "2107",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/31/2012",
          "CultureSourceNM": "STOOL",
          "OrganismDSC": "CLOSTRIDIUM DIFFICILE",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "49",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "49",
          "InfectionEventID": "12-33-HAI",
          "MRN": "621314",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-10T00:00:00",
          "DischargeDT": "2099-12-31T00:00:00",
          "EventTypeNM": "VRE",
          "HospitalAccountID": "11487288",
          "EpicPatientTypeDSC": "Surgical-Inpatient AM",
          "QuarterNM": "1Q",
          "MonthNM": "JAN",
          "LastNM": "WILLIAMS",
          "FirstNM": "JOSEPH",
          "MiddleNM": "NULL",
          "BirthDT": "1935-08-29T00:00:00",
          "AgeAtEventAMT": "76.0000",
          "GenderCD": "M",
          "FacilityNM": "TG Tacoma General Hospital (TG)",
          "DepartmentNM": "TG 4 OLYMPIC ADULT INTENSIVE CARE",
          "RoomNM": "471",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "1/31/2012",
          "CultureSourceNM": "SSI",
          "OrganismDSC": "ENTERCOCCUS FAECIUM",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      },
      {
        "data": {
          "ID": "50",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "50",
          "InfectionEventID": "12-34-HAI",
          "MRN": "1402048",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2012-01-31T00:00:00",
          "DischargeDT": "2012-02-13T00:00:00",
          "EventTypeNM": "CDIFF",
          "HospitalAccountID": null,
          "EpicPatientTypeDSC": "NULL",
          "QuarterNM": "1Q",
          "MonthNM": "FEB",
          "LastNM": "PUPPE",
          "FirstNM": "LORETTA",
          "MiddleNM": "NULL",
          "BirthDT": "1938-01-04T00:00:00",
          "AgeAtEventAMT": "74.0000",
          "GenderCD": "F",
          "FacilityNM": "Good Samaritan Hospital (GSH)",
          "DepartmentNM": "GSH 5 DALLY INTENSIVE CARE-CRITICAL CARE",
          "RoomNM": "525",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "YES",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "2/3/2012",
          "CultureSourceNM": "STOOL",
          "OrganismDSC": "CLOSTRIDIUM DIFFICILE",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      }
    ],
    "skip": 0,
    "top": 50
  }
  public oneInfectiousDiseaseRecord = {
    "count": 3493,
    "records": [
      {
        "data": {
          "ID": "1",
          "ModifiedDTS": "2021-02-03T11:35:00",
          "ModifiedUserNM": "MHS\\rbhart",
          "CreatedDTS": "2021-02-03T11:35:00",
          "CreatedUserNM": "MHS\\rbhart",
          "InfectionID": "1",
          "InfectionEventID": "19-1-HAI",
          "MRN": "2184880",
          "EventClassNM": "Hospital Acquired Infection-(HAI)",
          "AdmitDT": "2019-12-28T00:00:00",
          "DischargeDT": "2020-01-03T00:00:00",
          "EventTypeNM": "SSI-FUSN",
          "HospitalAccountID": "706551837",
          "EpicPatientTypeDSC": "Inpatient",
          "QuarterNM": "4Q",
          "MonthNM": "DEC",
          "LastNM": "TURNER-SAXTON",
          "FirstNM": "ETHEL",
          "MiddleNM": "NULL",
          "BirthDT": "1944-11-04T00:00:00",
          "AgeAtEventAMT": "-99.0000",
          "GenderCD": "F",
          "FacilityNM": "TG Tacoma General Hospital (TG)",
          "DepartmentNM": "GSH IPR",
          "RoomNM": "NULL",
          "PhysicianNM": "NULL",
          "ExpiredFLG": "NO",
          "ContributedToDeathFLG": "NULL",
          "CultureDT": "NULL",
          "CultureSourceNM": "NULL",
          "OrganismDSC": "NULL",
          "InjuryFLG": "1",
          "EventDT": "2099-12-31T00:00:00",
          "IncludeInSystemObjectiveFLG": "No"
        },
        "isUpdate": false,
        "subsets": {}
      }
    ],
    "skip": 0,
    "top": 1
  }

}
